name: build test
on: pull_request
jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: processing build
        run: npm run build
